# fly.toml app configuration file generated for my-game-tracker on 2023-12-13T00:37:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-game-tracker"
primary_region = "lax"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
